spring:
  application:
    name: surl-kdh

  data:
    redis:
      host: localhost
      port: 16379

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

geoip:
  mmdb:
    path: classpath:geoip/GeoLite2-Country.mmdb


mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.megastudy.surlkdh.domain.member.entity
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 1000
    default-statement-timeout: 30

logging:
  level:
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    com.megastudy.surlkdh: DEBUG

jwt:
  secret: ${JWT_SECRET}